// <auto-generated />
using System;
using IndianMovies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IndianMovies.Migrations
{
    [DbContext(typeof(IndianMoviesContext))]
    [Migration("20201210030335_IndianMovies")]
    partial class IndianMovies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IndianMovies.Models.Movies", b =>
                {
                    b.Property<int>("Movie_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actor_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actress_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Movie_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Release_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Movie_Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("IndianMovies.Models.MoviesCollection", b =>
                {
                    b.Property<int>("Moviescollection_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Australia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Canada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("India")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Movie_ID")
                        .HasColumnType("int");

                    b.Property<string>("Movie_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Movie_objMovie_Id")
                        .HasColumnType("int");

                    b.HasKey("Moviescollection_Id");

                    b.HasIndex("Movie_objMovie_Id");

                    b.ToTable("MoviesCollection");
                });

            modelBuilder.Entity("IndianMovies.Models.Ranking", b =>
                {
                    b.Property<int>("Ranking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Australia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Canada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("India")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Movie_ID")
                        .HasColumnType("int");

                    b.Property<string>("Movie_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Movie_objMovie_Id")
                        .HasColumnType("int");

                    b.HasKey("Ranking_Id");

                    b.HasIndex("Movie_objMovie_Id");

                    b.ToTable("Ranking");
                });

            modelBuilder.Entity("IndianMovies.Models.UpcomingMovies", b =>
                {
                    b.Property<int>("UpcomingMovies_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Movie_ID")
                        .HasColumnType("int");

                    b.Property<string>("Movie_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Movie_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Movie_objMovie_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Release_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("UpcomingMovies_Id");

                    b.HasIndex("Movie_objMovie_Id");

                    b.ToTable("UpcomingMovies");
                });

            modelBuilder.Entity("IndianMovies.Models.MoviesCollection", b =>
                {
                    b.HasOne("IndianMovies.Models.Movies", "Movie_obj")
                        .WithMany()
                        .HasForeignKey("Movie_objMovie_Id");
                });

            modelBuilder.Entity("IndianMovies.Models.Ranking", b =>
                {
                    b.HasOne("IndianMovies.Models.Movies", "Movie_obj")
                        .WithMany()
                        .HasForeignKey("Movie_objMovie_Id");
                });

            modelBuilder.Entity("IndianMovies.Models.UpcomingMovies", b =>
                {
                    b.HasOne("IndianMovies.Models.Movies", "Movie_obj")
                        .WithMany()
                        .HasForeignKey("Movie_objMovie_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
